# -*- coding: utf-8 -*-
"""questions plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ljrEm_2ui1MtxxHaJVgCEI_yKi8y6-QA
"""

import numpy as np
import matplotlib.pyplot as plt
# 1. Create a plot of y = x^3
x=np.linspace(-10,10,100)
y1=x**3
plt.plot(x,y1)
plt.title("Plot of y=x^3")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 2. Create a plot of sin(x) and cos(x) on the same plot
y2=np.sin(x)
y3=np.cos(x)
plt.plot(x,y2,label="sin(x)")
plt.plot(x,y3,label="cos(x)")
plt.legend()
plt.title("Plot of sin(x) and cos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 3. Create a plot of tan(x) and cot(x) on the same plot
y4=np.tan(x)
y5=1/np.tan(x)
plt.plot(x,y4,label="tan(x)")
plt.plot(x,y5,label="cot(x)")
plt.legend()
plt.title("Plot of tan(x) and cot(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 4. Create a plot of y = x^2 and y = x^3 on the same plot
y6=x**2
plt.plot(x,y6,label="y=x^2")
plt.plot(x,y1,label="y=x^3")
plt.legend()
plt.title("Plot of y=x^2 and y=x^3")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 5. Create a plot of y = x^2 and y = x^3 on the same plot with a legend
plt.plot(x,y6,label="y=x^2")
plt.plot(x,y1,label="y=x^3")
plt.legend()
plt.title("Plot of y=x^2 and y=x^3 with Legend")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 6. Create a plot of y = x^2 and y = x^3 on the same plot with a legend and a title
plt.plot(x,y6,label="y=x^2")
plt.plot(x,y1,label="y=x^3")
plt.legend()
plt.title("Plot of y=x^2 and y=x^3 with Legend and Title")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 7. Create a plot of y = x^2 and y = x^3 on the same plot with a legend, title, and axis labels
plt.plot(x,y6,label="y=x^2")
plt.plot(x,y1,label="y=x^3")
plt.legend()
plt.title("Plot of y=x^2 and y=x^3 with Legend, Title, and Axis Labels")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 8. Create a plot of y = x^2 and y = x^3 on the same plot with a legend, title, axis labels, and different colors
plt.plot(x,y6,label="y=x^2",color='blue')
plt.plot(x,y1,label="y=x^3",color='green')
plt.legend()
plt.title("Plot of y=x^2 and y=x^3 with Legend, Title, Axis Labels, and Colors")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 9. Create a scatter plot of y = x^2 and y = x^3 on the same plot with a legend, title, axis labels, different colors, and different line styles
plt.scatter(x,y6,label="y=x^2",color='blue',marker='o')
plt.scatter(x,y1,label="y=x^3",color='green',marker='x')
plt.legend()
plt.title("Scatter Plot of y=x^2 and y=x^3 with Legend, Title, Axis Labels, Colors, and Markers")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
# 10. Create a scatter plot of y=x^2 and y=x^3 on the same plot with a legend, title, axis labels, different colors, different line styles, and different markers
plt.scatter(x,y6,label="y=x^2",color='blue',marker='o')
plt.scatter(x,y1,label="y=x^3",color='green',marker='x')
plt.legend()
plt.title("Scatter Plot of y=x^2 and y=x^3 with Legend, Title, Axis Labels, Colors, Line Styles, and Markers")
plt.xlabel("x")
plt.ylabel("y")
plt.show()